In [9]:
import pandas as pd

def load_and_combine_data(file_path, labels):
    """
    Loads data from all sheets in an Excel file, assigns group labels, and combines the data.

    Parameters:
    - file_path (str): Path to the Excel file.
    - labels (list of str): List of labels for each sheet, in the same order as the sheets.

    Returns:
    - combined_df (DataFrame): A DataFrame with combined data from all sheets and group labels.
    """
    # Load the Excel file with all sheet names ADJUST file type if needed
    data = pd.read_excel(file_path, sheet_name=None)

    # Ensure there are enough labels for all sheets
    if len(labels) != len(data):
        raise ValueError("Number of labels must match the number of sheets.")

    # Combine the sheets, assigning the corresponding label to each
    combined_df_list = []
    for sheet_name, label in zip(data.keys(), labels):
        df = data[sheet_name]
        df['group'] = label
        combined_df_list.append(df)

    # Concatenate all DataFrames into one
    combined_df = pd.concat(combined_df_list, ignore_index=True)
    
    return combined_df

# Example usage
file_path = r'insert_file_path_here.xslx'
labels = ['Group One', 'Group Two']  # Make sure the number of labels matches the number of sheets
combined_data = load_and_combine_data(file_path, labels)

# Display the combined DataFrame
combined_data.head()

,Date,Product,Rating,Title,Review,group
0,2015-02-28,iRobot Roomba 650 for Pets,Five Stars,Five Stars,You would not believe how well this works,Group One
1,2015-01-12,iRobot Roomba 650 for Pets,Not Five Stars,Four Stars,You just walk away and it does the rest,Group One
2,2013-12-26,iRobot Roomba 650 for Pets,Five Stars,Awesome love it.,You have to Roomba proof your house but once t...,Group One
3,2015-08-17,iRobot Roomba 650 for Pets,Not Five Stars,Terrible Product - Ruined our Hardwood Floors!,Wow.. I don't know what to say. This thing wor...,Group One
4,2015-12-28,iRobot Roomba 650 for Pets,Five Stars,Super-impressed by how well it works!,"Wow, wow, WOW! I wanted to get one of these a...",Group One

In [ ]:
def con